# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://helpmercury.ru
title: TwoNik
email: helpmercury@mail.ru
author: TwoNik
description: > # "Write an awesome description for your new site here. 
  Регистрация в ФГИС Меркурий.
  Обучение работе в ФГИС Меркурий.
  Работа в ФГИС Меркурий.
copyright: 'Copyright &copy; 2021 TwoNik. All Rights Reserved.'
credits: 'Credits: Landing Page created by <a href="mail:berdsk.reklama@yandex.ru">berdsk.reklama</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
